name: Docker Image for GHCR

on: 
  release:
    types: [created]

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set Version Variable
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Build and push the image
      run: |
        docker login --username akajuliaan --password ${{ secrets.GITHUB_TOKEN }} ghcr.io
        docker build --tag ghcr.io/akajuliaan/filerun-sink-bridge:$RELEASE_VERSION --tag ghcr.io/akajuliaan/filerun-sink-bridge:latest .
        docker push ghcr.io/akajuliaan/filerun-sink-bridge --all-tags